version: "3.7"

services:
  reverse-proxy:
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    command: poetry run gunicorn checkers_backend:app -b 0.0.0.0:8000 -w 2 -k uvicorn.workers.UvicornWorker
    expose:
      - "8000"
    environment:
      - BACKEND_ROOT_PATH=/api
    labels:
      - traefik.enable=true
      - traefik.port=8000
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api
      - traefik.http.routers.backend.middlewares=api-strip-prefix@docker
  frontend:
    build:
      args:
        - CHECKERS_BACKEND=localhost/api
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web
