version: "3.7"

services:
  redis:
    image: redis
  backend:
    build: ./backend
    environment:
      - BROADCAST_URL=redis://redis:6379
  frontend:
    build: ./frontend
    depends_on:
      - backend
